#pragma once

#include <array>
#include <cstddef>
#include <cstdint>
#include <string_view>

#include "attadipa/core/availability.h"
#include "attadipa/core/clock.h"
#include "attadipa/core/transport_state.h"

namespace attadipa::core {

inline constexpr std::size_t kMeshPublicKeyBytes = 32;
inline constexpr std::size_t kMeshPeerNameBytes = 32;
inline constexpr std::size_t kMeshTextBytes = 128;

struct MeshPeerId {
    std::array<std::uint8_t, kMeshPublicKeyBytes> public_key{};

    friend bool operator==(const MeshPeerId& left, const MeshPeerId& right)
    {
        return left.public_key == right.public_key;
    }
};

struct MeshPeer {
    MeshPeerId id{};
    std::array<char, kMeshPeerNameBytes + 1> name{};
};

// WHAT THE WIRE HAD TO DO TO PRODUCE EACH OF THESE, and `Failed` is not among
// them because nothing observable on this protocol licenses it. ADR-0023 is the
// argument; the short form is that a companion client receives exactly two
// outbound delivery events -- the node accepted the message, and a matching
// acknowledgement came back -- and no third event that means anything negative.
// `MyMesh::onSendTimeout()` is an empty function body upstream, so the absence
// of a confirmation is the only negative signal there is, and it is produced
// equally by a message that never arrived and by one that arrived while its
// acknowledgement was lost on the way back.
//
// `None`         no request has been made in this session.
// `Queued`       the frame is in this client's transmit ring. Not: the node has it.
// `Accepted`     RESP_CODE_SENT arrived for this request. Not: it was transmitted,
//                or received.
// `Confirmed`    PUSH_CODE_SEND_CONFIRMED matched this request's ack tag. Never a
//                read receipt: the acknowledgement is generated by the recipient's
//                *node* and nothing in this protocol carries a read.
// `Unconfirmed`  the acknowledgement budget expired with no match, AFTER
//                `Accepted`. It means: the node accepted this, and this product
//                cannot tell whether it arrived. It is not a softer `Failed` --
//                `Failed` invites a resend and this says a resend may duplicate.
// `Refused`      the node answered RESP_CODE_ERR for a command it had accepted, a
//                room login failed, or this client could not put the frame on the
//                radio after it had already published `Queued`. Nothing reached
//                the air, so a resend cannot duplicate anything.
// `Unknown`      the request was made and no verdict followed: the session ended,
//                or the budget expired BEFORE `Accepted`, the node having answered
//                neither the text nor the room login. Not: it was not sent -- a
//                frame that left this client's ring may already have been written
//                to the characteristic.
//
// A LOCAL REFUSAL IS NOT IN THIS ENUM AT ALL. "The link is down", "a send is
// already in flight", "the body is over budget" are answers to the *call*: no
// message exists, so no message has a state. `MeshSendResult` below is where
// those live.
enum class MeshDelivery : std::uint8_t {
    None,
    Queued,
    Accepted,
    Confirmed,
    Unconfirmed,
    Refused,
    Unknown,
};

// WHY THE CALL ANSWERS WITH A REASON AND NOT WITH `false`. Four different
// refusals arrived as one `false` before ADR-0023, and one of them additionally
// wrote `MeshDelivery::Failed` -- a delivery verdict for a message that was
// never built. A caller told "no" has to be able to say which no, because the
// remedies differ: wait for the link, wait for the send in flight, shorten the
// body, fix the clock.
enum class MeshSendRefusal : std::uint8_t {
    None,                 // Not a refusal. A request id was issued.
    LinkNotReady,         // No session, or the node has not identified itself yet.
    Busy,                 // One send at a time, all the way to a terminal outcome.
    EmptyBody,            // Nothing to send.
    BodyTooLong,          // Over `kMeshTextBytes`, counted in bytes.
    BodyNotUtf8,          // Not well-formed UTF-8 -- in particular, already cut
                          // through a code point by whoever shortened it.
    TimestampOutOfRange,  // Before the epoch, or past what the frame's u32 holds.
    RoomPasswordInvalid,  // Empty, or longer than the login frame allows.
    RingFull,             // This client's own transmit ring had no slot.
    // A contacts walk is streaming, and its frames and the reply to a
    // fetch-by-key are the same response code. Only one of the two may own that
    // arm at a time, so a send to a recipient this client does not hold waits
    // for the walk. A send to one it does hold is unaffected.
    ContactsBusy,
};

// EITHER A NON-ZERO LOCAL REQUEST ID, OR A REFUSAL WITH A REASON. Never both,
// and never neither.
//
// The id is local and the word is the contract: it is explicitly NOT the node's
// four-byte acknowledgement tag, which is a keyed hash of timestamp, attempt and
// text and repeats for identical messages in the same second -- the recipient's
// key is not even an input. That tag is a correlation hint that can repeat, and
// a correlator written as if it were unique would attribute one message's
// confirmation to another. Non-zero so that zero means "no request".
struct MeshSendResult {
    std::uint32_t request_id = 0;
    MeshSendRefusal refusal = MeshSendRefusal::None;

    bool accepted() const { return request_id != 0; }
};

// WHETHER THE RETAINED CONTACT LIST IS THE NODE'S LIST, which is a different
// question from whether the walk that read it finished. The node's table can be
// appended to, rewritten in place or compacted under its own iterator, and it
// announces that with a push while the walk is still running --
// `docs/research/MESHCORE_CONTACT_SNAPSHOT_CONSISTENCY.md:190` — "**YES.** The one code that covers both"
// -- so a stream that ended is not a snapshot that is true. ADR-0022 decision 2
// keeps the two apart rather than folding consistency into `peers_complete`,
// which means the stream finished and must keep meaning that.
//
// `None` is a session that has not finished a walk yet, not a bad snapshot.
// `Dirty` is finished and unproven with a re-read still owed; `RetryPending`
// is one on the wire; `Degraded` is the newest read the *node ended* published
// anyway because the budget of two is spent -- a list that is probably right
// serves the wearer better than none, provided it does not claim to be proven.
// "The node ended" is the whole of the qualifier: a re-read closed by the
// three-second quiet sweep is a fragment, not a read, and is discarded, so
// `Degraded` can be a list two attempts old. A caller may rely on its being
// complete and on nothing else.
//
// NOTHING ON THE FACE READS THIS YET, and that is deliberate rather than
// unfinished: telling the wearer a peer list is unproven is a UI state with a
// Russian string and a place on two panel geometries behind it, and `ui/AGENTS.md`
// is where that is argued. Its first consumer is #552's recipient resolution,
// which needs to refuse rather than to display.
enum class MeshSnapshot : std::uint8_t {
    None,
    Consistent,
    Dirty,
    RetryPending,
    Degraded,
};

struct AttachedNodeBattery {
    // Provider topology, independent of whether a reading is available. An
    // integrated provider leaves this false: it shares the watch's supply.
    bool separate_supply = false;
    // Node-reported voltage, never state of charge or proof a cell is fitted.
    // The source's sample age and physical accuracy are not reported.
    std::uint16_t millivolts = 0;
    Validity validity = Validity::Unknown;
    // Last successful nonzero reading received in this session. Failed
    // refreshes retain its value/time but cannot keep it Valid.
    MonotonicTime received_at{};
};

struct MeshStatus {
    Availability availability = Availability::Unreachable;
    TransportPhase transport = TransportPhase::Absent;
    std::array<char, kMeshPeerNameBytes + 1> node_name{};
    // The node's own public key, from RESP_CODE_SELF_INFO. `node_name` is not
    // an identity: the bench ran two nodes whose names differed by an emoji and
    // whose advertisements are interchangeable to `advertises_meshcore()`
    // (docs/research/MESHCORE_T114_FIRST_CONTACT.md:63 "public key"). This is
    // what tells them apart, and it is not permanent either -- a factory reset
    // on the node regenerates it
    // (`docs/research/MESHCORE_T114_FIRST_CONTACT.md:50` "a factory reset
    // regenerates it"), which is a new identity by design and is meant to be
    // visible as one.
    MeshPeerId node_id{};
    bool has_node_id = false;
    // Belongs to node_id above, not to the selected remote mesh destination.
    AttachedNodeBattery node_battery{};
    // WHICH NODE THIS WATCH IS PINNED TO, AND THE LAST ONE IT TURNED AWAY.
    //
    // Unlike `node_id` above, neither is session state, and a disconnect does
    // not clear them. That is the point of them: a watch that refuses the only
    // node in range ends up with no session at all, so everything session-scoped
    // on the mesh screen is empty exactly when an operator most needs to know
    // why -- and the way out, the entry screen's node field (#411), is one an
    // operator goes looking for only if this screen says the watch is silent
    // on purpose.
    //
    // `has_refused` is set when a handshake reads a key that is not `pinned_id`,
    // and cleared when one reads a key that is. Nothing else clears it; in
    // particular a reconnect does not.
    MeshPeerId pinned_id{};
    bool has_pinned = false;
    MeshPeerId refused_id{};
    bool has_refused = false;
    std::array<char, kMeshPeerNameBytes + 1> last_sender{};
    std::array<char, kMeshTextBytes + 1> last_message{};
    MeshDelivery delivery = MeshDelivery::None;
    // WHICH REQUEST `delivery` IS ABOUT. Zero when there has been none in this
    // session. It is the id `send_private()` returned, kept so that a caller
    // reading a verdict can tell whether it is the one it asked for -- there is
    // one slot for a verdict and a second send overwrites it.
    std::uint32_t request_id = 0;
    std::uint16_t mtu = 0;
    std::uint16_t peers_reported = 0;
    std::uint16_t peers_retained = 0;
    std::int8_t snr_quarter_db = 0;
    bool has_snr = false;
    // Set when the node's contacts iteration has finished, cleared when one
    // starts. It is what makes `peers_retained` comparable to
    // `peers_reported`: mid-sync the retained count is climbing from zero
    // while the reported total is already final, and a pair printed then
    // counts up through 3/40. It replaces the old truncation flag, which only
    // ever meant "the 16 slots filled" -- a contact the watch drops by advert
    // type never reached that flag and is the ordinary case, not the corner.
    bool peers_complete = false;
    // Consistency, kept beside completeness and never folded into it. The two
    // move independently: a truncated list can be consistent, and a full one
    // that the node rewrote under its own iterator is not.
    MeshSnapshot snapshot = MeshSnapshot::None;
    bool message_truncated = false;
};

class MeshProvider {
public:
    virtual ~MeshProvider() = default;

    virtual MeshStatus status() const = 0;
    virtual std::size_t peer_count() const = 0;
    virtual bool peer(std::size_t index, MeshPeer& out) const = 0;
    virtual MeshSendResult send_private(const MeshPeerId& peer,
                                        std::string_view text,
                                        WallTime timestamp) = 0;
};

class MeshService {
public:
    explicit MeshService(MeshProvider& provider) : provider_(provider) {}

    MeshStatus status() const { return provider_.status(); }
    std::size_t peer_count() const { return provider_.peer_count(); }
    bool peer(std::size_t index, MeshPeer& out) const
    {
        return provider_.peer(index, out);
    }
    MeshSendResult send_private(const MeshPeerId& peer, std::string_view text,
                                WallTime timestamp)
    {
        return provider_.send_private(peer, text, timestamp);
    }

private:
    MeshProvider& provider_;
};

const char* to_string(MeshDelivery delivery);
const char* to_string(MeshSendRefusal refusal);

// THE LENGTH OF THE LONGEST WELL-FORMED UTF-8 PREFIX OF `text` THAT IS AT MOST
// `limit` BYTES. Zero for a body that starts with a continuation byte or an
// over-long form.
//
// It exists so that shortening happens at a code-point boundary and nowhere
// else: a Russian phrase is about two bytes a letter and a single emoji is four,
// so a byte budget cut with `substr` splits a character roughly half the time in
// this product's second language. The send path does not call it to repair
// anything -- over budget is a refusal the owner sees before sending, never a
// silent truncation -- it calls it to decide whether the body it was handed is
// well formed at all.
//
// The algorithm is MeshCore's `mesh::validUtf8PrefixLength`
// (`src/helpers/UTF8Helpers.h` at `d929643`, MIT), which is unused at that
// revision: this is an extracted algorithm and not a dependency on a firmware
// this product does not link.
std::size_t utf8_prefix_length(std::string_view text, std::size_t limit);

}  // namespace attadipa::core
