#!/usr/bin/env python3
"""Hold `lvgl_inventory.py` against the LVGL headers it claims to describe.

`check_raw_values.py` refuses raw pixel counts, durations and colours in screen
code, and it can only refuse what it knows about. Its inventory is written down
rather than derived, because the simulator — and therefore LVGL — is `OFF` by
default and a checker that needs LVGL on disk is a checker that stops running.

A written-down list is checked by *example*, and issue #68's follow-up is what
that costs: `lv_obj_set_ext_click_area(obj, 12)` passed, because the list was
never held against the header it said it came from. So this is the other half.
Wherever LVGL *is* on disk — the simulator build, and every CI job that
configures it — every entry point LVGL declares must be classified, by name:

* in `ENTRY_POINTS`, saying which arguments are a length, a duration or a
  colour; or
* in `NOT_A_DESIGN_VALUE`, saying what its numbers are instead.

There is no third answer and no default, so a setter LVGL grows is reported by
name rather than silently unchecked. The check runs in both directions — an
inventory entry LVGL no longer declares is also an error, because a renamed
function that still appears in our list is a rule that no longer bites and
nothing would say so.

Usage:
    check_inventory.py [LVGL_SOURCE_DIR]

The directory is the root of an LVGL checkout — the one holding `lv_version.h`
and `src/`. Without an argument it reads `ATTADIPA_LVGL_SOURCE_DIR`, then looks
for a tree FetchContent has already left under `build*/_deps/lvgl-src`.

Exit 0 when the inventory is complete; 1 with one line per discrepancy
otherwise; 2 when no LVGL tree could be found, which is a different thing and
must not read as a pass.
"""

from __future__ import annotations

import os
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

import lvgl_api                      # noqa: E402
import lvgl_inventory as inventory   # noqa: E402

ROOT = Path(__file__).resolve().parents[2]

# The version lvgl_inventory.py was derived from. A bump has to come back
# through here, which is the point: docs/research/DEPENDENCIES.md carries
# re-deriving the inventory as a step of an LVGL bump, and this is what makes
# forgetting it fail rather than pass quietly.
DERIVED_FROM = "9.5.0"

STYLE_PREFIXES = ("lv_obj_set_style_", "lv_style_set_")


def find_lvgl(argv: list[str]) -> Path | None:
    if argv:
        return Path(argv[0]).resolve()
    from_env = os.environ.get("ATTADIPA_LVGL_SOURCE_DIR", "").strip()
    if from_env:
        return Path(from_env).resolve()
    for build in sorted(ROOT.glob("build*")):
        candidate = build / "_deps" / "lvgl-src"
        if (candidate / "src").is_dir():
            return candidate
    return None


def style_property(name: str) -> str | None:
    for prefix in STYLE_PREFIXES:
        if name.startswith(prefix):
            return name[len(prefix):]
    return None


def check(root: Path) -> list[str]:
    problems: list[str] = []

    found = lvgl_api.entry_points(root)
    if not found:
        return [f"no LVGL declarations found under {root}/src — is that an "
                f"LVGL checkout?"]

    classified = set(inventory.ENTRY_POINTS)
    excused = set(inventory.NOT_A_DESIGN_VALUE)
    known_properties = inventory.style_property_names()

    for name in sorted(classified & excused):
        problems.append(
            f"{name} is in both ENTRY_POINTS and NOT_A_DESIGN_VALUE — it takes "
            f"a design value or it does not")

    # --- every entry point LVGL declares is accounted for -------------------
    for name in sorted(found):
        entry = found[name]
        if name in classified or name in excused:
            continue    # named outright, which beats being generated by shape
        prop = style_property(name)
        if prop is not None:
            if prop not in known_properties:
                problems.append(
                    f"{name}: LVGL declares style property '{prop}' with a "
                    f"numeric value and lvgl_inventory.py does not classify "
                    f"it. Add it to LENGTH_PROPERTIES, DURATION_PROPERTIES or "
                    f"NOT_A_DESIGN_VALUE_PROPERTIES — {entry.header}")
            continue
        where = f"{entry.header}" + (f", an alias of {entry.alias_of}"
                                     if entry.alias_of else "")
        problems.append(
            f"{name}: unclassified. LVGL declares it with numeric argument(s) "
            f"{', '.join(entry.parameters[i] for i in entry.numeric)} and "
            f"lvgl_inventory.py has no opinion. Put it in ENTRY_POINTS if one "
            f"of them is a length, a duration or a colour, and in "
            f"NOT_A_DESIGN_VALUE with a reason if none is — {where}")

    # --- and nothing is claimed that LVGL no longer declares ----------------
    for name in sorted(classified | excused):
        if style_property(name) is not None and name not in found:
            # A style setter is generated from a property name, so a property
            # that has gone is reported once below rather than twice here.
            continue
        if name not in found:
            problems.append(
                f"{name}: in lvgl_inventory.py and LVGL {DERIVED_FROM} does "
                f"not declare it. Renamed or removed — the rule it carries is "
                f"no longer being applied to anything")

    declared_properties = {
        style_property(name) for name in found if style_property(name)}
    for prop in sorted(known_properties - declared_properties):
        problems.append(
            f"style property '{prop}': classified in lvgl_inventory.py and "
            f"LVGL {DERIVED_FROM} declares no numeric setter for it")

    # --- the argument positions are real, and all of them are accounted for -
    for name, positions in sorted(inventory.ENTRY_POINTS.items()):
        entry = found.get(name)
        if entry is None:
            continue    # already reported above
        listed = {index for index, _ in positions}
        for index, kind in positions:
            parameter = entry.numeric_parameter(index)
            if parameter is None:
                problems.append(
                    f"{name}: argument {index} is called a {kind} and the "
                    f"signature has only {len(entry.parameters)} arguments — "
                    f"{entry.signature}")
            elif index not in entry.numeric:
                problems.append(
                    f"{name}: argument {index} is called a {kind} and LVGL "
                    f"declares it '{parameter}', which is not a number — "
                    f"{entry.signature}")
        unaccounted = [index for index in entry.numeric
                       if index not in listed
                       and index not in inventory.OTHER_ARGUMENTS.get(name, {})]
        for index in unaccounted:
            problems.append(
                f"{name}: argument {index} ('{entry.parameters[index]}') is a "
                f"number and nothing says what it is. Add it to ENTRY_POINTS "
                f"if it carries a design value, and to OTHER_ARGUMENTS with a "
                f"reason if it does not — {entry.signature}")

    for name, positions in sorted(inventory.OTHER_ARGUMENTS.items()):
        entry = found.get(name)
        if entry is None:
            problems.append(
                f"{name}: in OTHER_ARGUMENTS and LVGL {DERIVED_FROM} does not "
                f"declare it")
            continue
        for index in sorted(positions):
            if index not in entry.numeric:
                problems.append(
                    f"{name}: OTHER_ARGUMENTS excuses argument {index}, which "
                    f"is not a numeric argument of {entry.signature}")

    return problems


def main(argv: list[str]) -> int:
    root = find_lvgl(argv)
    if root is None or not (root / "src").is_dir():
        print("check_inventory: no LVGL source tree found. Pass its path, set "
              "ATTADIPA_LVGL_SOURCE_DIR, or configure the simulator "
              "(-DATTADIPA_BUILD_SIMULATOR=ON) so FetchContent leaves one "
              "under build/_deps/lvgl-src.\n"
              "This is not a pass: the inventory in tools/ui/lvgl_inventory.py "
              "was not checked against anything.", file=sys.stderr)
        return 2

    version = lvgl_api.version(root)
    if version is None:
        print(f"check_inventory: {root} has no readable lv_version.h, so there "
              f"is no way to know which LVGL the inventory was just checked "
              f"against.", file=sys.stderr)
        return 2
    if version != DERIVED_FROM:
        print(f"check_inventory: this tree is LVGL {version} and "
              f"tools/ui/lvgl_inventory.py was derived from {DERIVED_FROM}.\n"
              f"Re-derive it — docs/research/DEPENDENCIES.md carries that as a "
              f"step of an LVGL bump, because a list cannot notice a setter "
              f"LVGL adds.", file=sys.stderr)
        return 1

    problems = check(root)
    for problem in problems:
        print(f"check_inventory: {problem}", file=sys.stderr)
    if problems:
        print(f"\n{len(problems)} inventory problem(s) against LVGL {version} "
              f"at {root}.\nThe inventory is tools/ui/lvgl_inventory.py; the "
              f"scan that reads it is tools/ui/check_raw_values.py.",
              file=sys.stderr)
        return 1

    entry_points = len(inventory.ENTRY_POINTS)
    excused = len(inventory.NOT_A_DESIGN_VALUE)
    print(f"check_inventory: LVGL {version} at {root} — {entry_points} entry "
          f"point(s) carry a design value, {excused} deliberately do not, "
          f"nothing unclassified")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))

