#!/usr/bin/env python3
"""Generate the UI font subsets, and verify the checked-in ones are current.

Why generated files live in the repository at all: the alternative is running
lv_font_conv during the build, which puts Node.js between a contributor and a
green build for a file that changes when somebody edits charset.py — about once
a quarter. The l10n catalogue already made this trade (`gen_strings.py --check`)
and this follows it: the output is committed, and a test fails when it drifts.

The owner references choose Nunito Sans. Google Fonts publishes it as a
variable font whose default weight is ExtraLight 200, so generation pins the
measured Regular 400 instance before conversion. Direction arrows remain icons,
matching the image pipeline and avoiding glyphs Nunito Sans does not contain.

**The provenance line is rewritten, and that is not cosmetic.** lv_font_conv
records its own argv in an `Opts:` comment, which means the absolute path of
whoever's machine ran it — `/mnt/e/projects/...` in the first generation — is
baked into a shipping asset. Two consequences, both bad: a fresh generation on
any other machine differs from the committed file in bytes while being identical
in every glyph, so the only byte-for-byte check available was guaranteed to
report a false positive; and provenance that changes with the checkout is
provenance that cannot be hashed. The line is normalized to logical paths and
told the truth instead — the source TTF's SHA-256 and the converter's pinned
version go in the banner, where they mean something on every machine.
"""

from __future__ import annotations

import argparse
import hashlib
import os
import re
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
OUT_DIR = ROOT / "assets" / "fonts" / "generated"

sys.path.insert(0, str(Path(__file__).resolve().parent))
sys.path.insert(0, str(ROOT / "tools" / "integrity"))
import charset  # noqa: E402
import stamp  # noqa: E402

# The text sizes the screens actually ask for. 64 and 96 are the first true
# `type.display` faces: the smaller four remain UI text, while a watch face at
# 28 px is a status line pretending to be a clock.
SIZES = (14, 16, 20, 28, 64, 96)

# Canonical owner-reference face, pinned to the Google Fonts commit measured in
# docs/research/FONT_MEASUREMENTS.md. The downloaded variable face defaults to
# weight 200; tools/font/instantiate.py pins Regular 400 before conversion.
TTF_PATH = Path("ofl/nunitosans/NunitoSans[YTLC,opsz,wdth,wght].ttf")
TTF_COMMIT = "a0e524c05906bece66cd5bcdc9216ff1d044fcbf"
TTF_SHA256 = "f934d7142fb4784bf828da485b7dcbd90c0c80d514e9d49a5da0ed3a1ae2491d"
FONT_WEIGHT = 400

# docs/research/DEPENDENCIES.md pins it, and this refuses to run anything else.
# The banner in every generated file names this version, so a converter that is
# not this one would make the file claim a provenance it does not have — and a
# bump is a decision that needs the subset re-measured, not something a machine
# with a newer npm cache does by accident.
CONVERTER_VERSION = "1.5.3"

BPP = 4

# What the `Opts:` line says instead of two absolute paths. Neither is a path a
# tool ever opens: they are the two inputs named where a reader can find them —
# the file inside whatever LVGL tree the build pinned, and the output's home in
# this repository.
LOGICAL_TTF = f"<google-fonts>/{TTF_PATH.as_posix()}@{TTF_COMMIT};wght={FONT_WEIGHT}"
OPTS_LINE = re.compile(r"^ \* Opts: .*$", re.MULTILINE)


def output_name(size: int) -> str:
    return f"attadipa_nunito_sans_{size}.c"


def outputs() -> list[Path]:
    """Every file this generator is responsible for, in size order."""
    return [OUT_DIR / output_name(size) for size in SIZES]


def logical_output(size: int) -> str:
    return (OUT_DIR / output_name(size)).relative_to(ROOT).as_posix()


def converter_arguments(font: str, destination: str, size: int) -> list[str]:
    """The converter's argv, with the two paths left to the caller.

    One function for both the real invocation and the normalized `Opts:` line,
    so the provenance a generated file claims cannot drift from the command that
    produced it. Two lists that were meant to agree eventually do not.
    """
    arguments = [
        "--font", font,
        "--size", str(size),
        "--bpp", str(BPP),
        "--format", "lvgl",
        "--no-compress",
        "--lv-include", "lvgl.h",
        "-o", destination,
    ]
    for range_argument in charset.as_lv_font_conv_ranges():
        arguments += ["--range", range_argument]
    return arguments


def banner(size: int) -> str:
    """The header prepended to every generated file.

    It carries the provenance the converter's own comment cannot: which bytes of
    Nunito Sans, converted by which pinned version. Both are checkable on any
    machine, which is the difference between provenance and decoration.
    """
    return (
        "/*\n"
        " * GENERATED by tools/font/generate_ui_fonts.py — do not edit.\n"
        " *\n"
        f" * Nunito Sans Regular {FONT_WEIGHT}, subset to the {len(charset.codepoints())}\n"
        f" * codepoints in tools/font/charset.py, at {size} px, {BPP} bpp.\n"
        " * SIL Open Font License 1.1 — assets/fonts/OFL.txt.\n"
        " *\n"
        f" * Variable source TTF SHA-256: {TTF_SHA256}\n"
        f" * Converter: lv_font_conv {CONVERTER_VERSION} (docs/research/DEPENDENCIES.md)\n"
        f" * Variable source pinned to wght={FONT_WEIGHT} before conversion.\n"
        " */\n"
    )


def find_ttf(explicit: str | None) -> Path:
    if explicit:
        return Path(explicit)
    for candidate in sorted(Path("/tmp").glob(f"**/{TTF_PATH.name}")):
        return candidate
    raise SystemExit(
        f"{TTF_PATH.name} not found. Run tools/font/fetch_ttf.py --out /tmp/"
        f"{TTF_PATH.name}, or pass --ttf.")


def instantiate_ttf(source: Path, destination: Path) -> None:
    result = subprocess.run(
        [sys.executable, str(Path(__file__).parent / "instantiate.py"),
         str(source), str(destination), f"wght={FONT_WEIGHT}"],
        capture_output=True, text=True)
    if result.returncode != 0:
        raise SystemExit(f"could not pin Nunito Sans weight:\n{result.stderr}")


def find_converter(explicit: str | None) -> list[str]:
    if explicit:
        return [explicit]
    found = shutil.which("lv_font_conv")
    if found:
        return [found]
    for base in (ROOT, Path(os.environ.get("TMPDIR", "/tmp"))):
        local = base / "node_modules" / ".bin" / "lv_font_conv"
        if local.exists():
            return [str(local)]
    raise SystemExit(
        f"lv_font_conv not found. npm install --no-save lv_font_conv@{CONVERTER_VERSION}, "
        "or pass --converter.")


def check_converter_version(converter: list[str]) -> None:
    """Refuse a converter that is not the pinned one.

    Never trust, verify, applied to a tool rather than to a board: `--converter`
    accepts any path, `shutil.which` finds whatever is on PATH, and a global npm
    install is exactly how "latest" gets run by accident. The generated files
    would then claim 1.5.3 in their banner and be something else.
    """
    result = subprocess.run([*converter, "--version"], capture_output=True, text=True)
    reported = result.stdout.strip() or result.stderr.strip()
    if result.returncode != 0:
        raise SystemExit(
            f"{converter[0]} --version exited {result.returncode}. That is not a "
            f"working lv_font_conv:\n{result.stderr.strip()}")
    if reported != CONVERTER_VERSION:
        raise SystemExit(
            f"{converter[0]} is lv_font_conv {reported}, and this pipeline is pinned to "
            f"{CONVERTER_VERSION} (docs/research/DEPENDENCIES.md).\n"
            f"A bump changes bytes that ship in flash, so it means re-measuring the "
            f"subset and updating the pin — not generating with whatever is installed.\n"
            f"  npm install --no-save lv_font_conv@{CONVERTER_VERSION}")


def generate(ttf: Path, converter: list[str], destination: Path, size: int) -> None:
    command = [*converter, *converter_arguments(str(ttf), str(destination), size)]

    result = subprocess.run(command, capture_output=True, text=True)
    if result.returncode != 0:
        raise SystemExit(f"lv_font_conv failed for size {size}:\n{result.stderr}")

    # lv_font_conv names the symbol after the output file, which is what the
    # header declares. Nothing to rewrite there — but the generated file carries
    # no provenance of its own beyond an `Opts:` line full of one machine's
    # absolute paths, so that line is normalized and a banner is prepended. A
    # generated file that does not say it is generated gets edited by hand
    # exactly once.
    body = destination.read_text(encoding="utf-8")
    canonical = " ".join(converter_arguments(LOGICAL_TTF, logical_output(size), size))
    body, replaced = OPTS_LINE.subn(lambda _: f" * Opts: {canonical}", body)
    if replaced != 1:
        # Not a warning. The whole reproducibility argument rests on this line
        # being found and rewritten; if the converter's banner format ever
        # changes, generating anyway would commit an absolute path again and the
        # next machine's check would fail for a reason nobody could see.
        raise SystemExit(
            f"lv_font_conv wrote {replaced} 'Opts:' lines for size {size}, expected "
            f"exactly 1. Its output format has changed, and the normalization in "
            f"tools/font/generate_ui_fonts.py has to change with it.")
    destination.write_text(banner(size) + body, encoding="utf-8", newline="\n")


def stamp_path() -> Path:
    return OUT_DIR / "INPUTS.sha256"


def inputs_digest() -> str:
    """Everything that decides what the generated bytes are.

    Deliberately not a hash of this whole file. The output depends on the
    charset, the sizes, the bit depth, the source TTF, the converter version and
    the exact text of the banner and the `Opts:` line — so those are hashed, and
    a comment edited in this module does not demand a regeneration that would
    need Node on a machine that has none. What it *does* mean is that changing a
    word of the banner fails the check until the fonts are rebuilt, which is
    correct: that word is in the shipped file.
    """
    digest = hashlib.sha256()
    digest.update(TTF_SHA256.encode())
    digest.update(
        f"commit={TTF_COMMIT} weight={FONT_WEIGHT} bpp={BPP} sizes={SIZES} "
        f"converter={CONVERTER_VERSION}".encode())
    digest.update((Path(__file__).parent / "charset.py").read_bytes())
    for size in SIZES:
        digest.update(banner(size).encode())
        digest.update(
            " ".join(converter_arguments(LOGICAL_TTF, logical_output(size), size)).encode())
    return digest.hexdigest()


STAMP_EXPLANATION = """\
What the generated fonts were built from, and what was built. The file is still
called INPUTS.sha256 because several documents cite it by name; it has recorded
outputs as well since issue #69, and this line is here so that nobody has to
infer that from the name.

`inputs` covers the charset, the sizes, the bit depth, the source TTF's hash,
the pinned converter version and the exact banner text. Each `output` line is
the SHA-256 of a committed file, so a hand-edited bitmap, a corrupted glyph
descriptor or a deleted size fails `--check` on a machine with neither Node nor
a configured build — which is most of them, and every host CI job.

Written only by tools/font/generate_ui_fonts.py. Editing a line here to make a
check pass is the one repair that fixes nothing.\
"""


def write_stamp() -> None:
    stamp.write(stamp_path(), STAMP_EXPLANATION, inputs_digest(), outputs())


def check_against_stamp() -> int:
    problems = stamp.verify(stamp_path(), inputs_digest(), outputs())
    if problems:
        print(f"generate_ui_fonts: {OUT_DIR.relative_to(ROOT)} does not match its "
              f"stamp:\n", file=sys.stderr)
        for problem in problems:
            print(f"  * {problem}", file=sys.stderr)
        print("\nRun: python3 tools/font/generate_ui_fonts.py", file=sys.stderr)
        return 1
    print(f"fonts: {len(SIZES)} generated file(s) match their recorded hashes, "
          f"inputs unchanged")
    return 0


def check_against_fresh_generation(ttf: Path, converter: list[str]) -> int:
    """The expensive half: generate again and compare every byte.

    This is what the stamp cannot do — it proves the committed bytes are what
    this converter, this TTF and this charset actually produce, rather than what
    something once produced. It is only meaningful because the `Opts:` line is
    normalized; before that, a fresh generation differed by construction and
    this path could only ever cry wolf.
    """
    differences = []
    with tempfile.TemporaryDirectory() as directory:
        for size in SIZES:
            fresh = Path(directory) / output_name(size)
            generate(ttf, converter, fresh, size)
            committed = OUT_DIR / fresh.name
            if not committed.exists():
                differences.append(f"{fresh.name} is missing")
            elif committed.read_bytes() != fresh.read_bytes():
                differences.append(f"{fresh.name} differs from a fresh generation")

    # The stamp is checked as well, and not only as a formality: a tree whose
    # files are right and whose stamp is stale would pass every host job the
    # moment somebody regenerated by hand and forgot this file.
    differences += stamp.verify(stamp_path(), inputs_digest(), outputs())

    if differences:
        print(f"generate_ui_fonts: {OUT_DIR.relative_to(ROOT)} is not what "
              f"lv_font_conv {CONVERTER_VERSION} produces from these inputs:\n",
              file=sys.stderr)
        for difference in differences:
            print(f"  * {difference}", file=sys.stderr)
        print("\nRun: python3 tools/font/generate_ui_fonts.py", file=sys.stderr)
        return 1
    print(f"fonts: {len(SIZES)} generated file(s) are byte-for-byte what "
          f"lv_font_conv {CONVERTER_VERSION} produces, and the stamp agrees")
    return 0


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--ttf", help=f"path to {TTF_PATH.name}")
    parser.add_argument("--converter", help="path to lv_font_conv")
    parser.add_argument("--check", action="store_true",
                        help="regenerate into a temporary directory and compare")
    arguments = parser.parse_args()

    if arguments.check and not (arguments.ttf or arguments.converter):
        # The check has to be runnable on a machine with neither Node nor a
        # configured build — that is most machines, and most CI jobs. It falls
        # back to the stamp, which now binds the committed bytes as well as the
        # inputs, so it catches both cases that actually happen: somebody edits
        # charset.py and forgets the fonts, and somebody edits a generated file.
        return check_against_stamp()

    ttf = find_ttf(arguments.ttf)
    digest = hashlib.sha256(ttf.read_bytes()).hexdigest()
    if digest != TTF_SHA256:
        raise SystemExit(f"{ttf} hashes {digest}, expected {TTF_SHA256}")

    converter = find_converter(arguments.converter)
    check_converter_version(converter)

    with tempfile.TemporaryDirectory() as directory:
        instance = Path(directory) / "NunitoSans-400.ttf"
        instantiate_ttf(ttf, instance)
        if arguments.check:
            return check_against_fresh_generation(instance, converter)

        OUT_DIR.mkdir(parents=True, exist_ok=True)
        for size in SIZES:
            destination = OUT_DIR / output_name(size)
            generate(instance, converter, destination, size)
            print(f"{destination.relative_to(ROOT)}  {destination.stat().st_size:>7} bytes")

    write_stamp()
    return 0


if __name__ == "__main__":
    sys.exit(main())
