#!/usr/bin/env python3
"""Generate the UI font subsets, and verify the checked-in ones are current.

Why generated files live in the repository at all: the alternative is running
lv_font_conv during the build, which puts Node.js between a contributor and a
green build for a file that changes when somebody edits charset.py — about once
a quarter. The l10n catalogue already made this trade (`gen_strings.py --check`)
and this follows it: the output is committed, and a test fails when it drifts.

What it does **not** do is choose a typeface. Montserrat is here because LVGL
already ships it under OFL-1.1 at the revision this project pins, and because it
covers all 181 codepoints charset.py asks for. Which face the product uses is
open question D16 and final section 51 lists four things that must be checked
before either candidate is adopted. This is scaffolding that draws every
character correctly, which is the least a build may do; it is not a decision.
"""

from __future__ import annotations

import argparse
import hashlib
import os
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
import charset  # noqa: E402

ROOT = Path(__file__).resolve().parents[2]
OUT_DIR = ROOT / "assets" / "fonts" / "generated"

# The four sizes the screens actually ask for. `pick_font()` in the simulator
# maps a TypeRole and a panel width onto them; adding a fifth here without a
# caller is 15 kB of flash for nobody.
SIZES = (14, 16, 20, 28)

# The clock's own faces, and they are numerals only.
#
# A watch face wants a time that dominates the screen, which means 64 px on a
# 240 px panel and more on a 410 px one. At the full 181-codepoint charset that
# would be about 160 kB and 360 kB of .rodata — for a string that is only ever
# "09:41" or "--:--". Six characters cost about 4 % of that.
#
# The range is digits, colon, the two dashes the unknown-time placeholder uses,
# and the degree sign, which the navigation screens will want at this size for
# a bearing.
NUMERAL_SIZES = (64, 96)
NUMERAL_RANGES = ["0x0030-0x003A", "0x002D", "0x002E", "0x00B0"]

# LVGL ships this file under OFL-1.1 in its own tree. Taking it from there rather
# than from the internet means the font is pinned by the same commit as the
# library, which is one fewer thing that can drift.
TTF_IN_LVGL = Path("scripts/built_in_font/Montserrat-Medium.ttf")
TTF_SHA256 = "421f26b23e2be6b98373d32acd3cb2897b154d4bf0a77d26534ce476e4cbed53"

BPP = 4


def find_ttf(explicit: str | None) -> Path:
    if explicit:
        return Path(explicit)
    # Wherever LVGL was fetched to. Several build directories may exist; any of
    # them will do, because the hash is checked below.
    for candidate in sorted(ROOT.glob(f"build*/_deps/lvgl-src/{TTF_IN_LVGL}")):
        return candidate
    raise SystemExit(
        "Montserrat-Medium.ttf not found. Configure a build with "
        "-DATTADIPA_BUILD_SIMULATOR=ON first, so LVGL is fetched, or pass --ttf."
    )


def find_converter(explicit: str | None) -> list[str]:
    if explicit:
        return [explicit]
    found = shutil.which("lv_font_conv")
    if found:
        return [found]
    for base in (ROOT, Path(os.environ.get("TMPDIR", "/tmp"))):
        local = base / "node_modules" / ".bin" / "lv_font_conv"
        if local.exists():
            return [str(local)]
    raise SystemExit(
        "lv_font_conv not found. npm install --no-save lv_font_conv@1.5.3, "
        "or pass --converter."
    )


def generate(ttf: Path, converter: list[str], destination: Path, size: int,
             ranges: list[str] | None = None, what: str = "the 181 codepoints in "
                                                          "tools/font/charset.py") -> None:
    command = [
        *converter,
        "--font", str(ttf),
        "--size", str(size),
        "--bpp", str(BPP),
        "--format", "lvgl",
        "--no-compress",
        "--lv-include", "lvgl.h",
        "-o", str(destination),
    ]
    for range_argument in (ranges if ranges is not None
                           else charset.as_lv_font_conv_ranges()):
        command += ["--range", range_argument]

    result = subprocess.run(command, capture_output=True, text=True)
    if result.returncode != 0:
        raise SystemExit(f"lv_font_conv failed for size {size}:\n{result.stderr}")

    # lv_font_conv names the symbol after the output file, which is what the
    # header declares. Nothing to rewrite — but the generated file carries no
    # provenance of its own, so a banner is prepended. A generated file that does
    # not say it is generated gets edited by hand exactly once.
    body = destination.read_text(encoding="utf-8")
    banner = (
        "/*\n"
        " * GENERATED by tools/font/generate_ui_fonts.py — do not edit.\n"
        " *\n"
        f" * Montserrat Medium, subset to {what},\n"
        f" * at {size} px, {BPP} bpp. SIL Open Font License 1.1 — assets/fonts/OFL.txt.\n"
        " *\n"
        " * Scaffolding, not a typeface decision: open question D16, final section 51.\n"
        " */\n"
    )
    destination.write_text(banner + body, encoding="utf-8", newline="\n")


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--ttf", help="path to Montserrat-Medium.ttf")
    parser.add_argument("--converter", help="path to lv_font_conv")
    parser.add_argument("--check", action="store_true",
                        help="regenerate into a temporary directory and compare")
    arguments = parser.parse_args()

    if arguments.check and not (arguments.ttf or arguments.converter):
        # The check has to be runnable on a machine with neither Node nor a
        # configured build — that is most machines, and most CI jobs. It falls
        # back to a hash of the inputs, which catches the case that actually
        # happens: somebody edits charset.py and forgets the fonts.
        return check_against_stamp()

    ttf = find_ttf(arguments.ttf)
    digest = hashlib.sha256(ttf.read_bytes()).hexdigest()
    if digest != TTF_SHA256:
        raise SystemExit(f"{ttf} hashes {digest}, expected {TTF_SHA256}")

    converter = find_converter(arguments.converter)

    if arguments.check:
        with tempfile.TemporaryDirectory() as directory:
            differences = []
            wanted = ([(s, None, f"attadipa_montserrat_{s}.c") for s in SIZES] +
                      [(s, NUMERAL_RANGES, f"attadipa_montserrat_num_{s}.c")
                       for s in NUMERAL_SIZES])
            for size, ranges, name in wanted:
                fresh = Path(directory) / name
                generate(ttf, converter, fresh, size, ranges,
                         "digits, colon and degree" if ranges else
                         "the 181 codepoints in tools/font/charset.py")
                committed = OUT_DIR / fresh.name
                if not committed.exists():
                    differences.append(f"{fresh.name} is missing")
                elif committed.read_text(encoding="utf-8") != fresh.read_text(encoding="utf-8"):
                    differences.append(f"{fresh.name} differs from a fresh generation")
            if differences:
                for difference in differences:
                    print(difference, file=sys.stderr)
                print("\nRun: python3 tools/font/generate_ui_fonts.py", file=sys.stderr)
                return 1
        print(f"fonts: {len(SIZES) + len(NUMERAL_SIZES)} generated file(s) are current")
        return 0

    OUT_DIR.mkdir(parents=True, exist_ok=True)
    for size in SIZES:
        destination = OUT_DIR / f"attadipa_montserrat_{size}.c"
        generate(ttf, converter, destination, size)
        print(f"{destination.relative_to(ROOT)}  {destination.stat().st_size:>7} bytes")
    for size in NUMERAL_SIZES:
        destination = OUT_DIR / f"attadipa_montserrat_num_{size}.c"
        generate(ttf, converter, destination, size, NUMERAL_RANGES,
                 "digits, colon and degree")
        print(f"{destination.relative_to(ROOT)}  {destination.stat().st_size:>7} bytes")

    write_stamp()
    return 0


def stamp_path() -> Path:
    return OUT_DIR / "INPUTS.sha256"


def inputs_digest() -> str:
    digest = hashlib.sha256()
    digest.update(TTF_SHA256.encode())
    digest.update(f"bpp={BPP} sizes={SIZES} num={NUMERAL_SIZES} {NUMERAL_RANGES}".encode())
    digest.update((Path(__file__).parent / "charset.py").read_bytes())
    return digest.hexdigest()


def write_stamp() -> None:
    stamp_path().write_text(
        "# What the generated fonts were built from. Compared by --check on a\n"
        "# machine with no Node and no configured build, which is most of them.\n"
        f"{inputs_digest()}\n",
        encoding="utf-8", newline="\n")


def check_against_stamp() -> int:
    stamp = stamp_path()
    if not stamp.exists():
        print(f"{stamp} is missing — the fonts have never been generated", file=sys.stderr)
        return 1
    recorded = [line for line in stamp.read_text(encoding="utf-8").splitlines()
                if line and not line.startswith("#")]
    if recorded != [inputs_digest()]:
        print("the font inputs changed since the generated files were written.\n"
              "charset.py, the size list, the bit depth or the source TTF is not\n"
              "what assets/fonts/generated was built from.\n\n"
              "Run: python3 tools/font/generate_ui_fonts.py", file=sys.stderr)
        return 1
    missing = [n for n in ([f"attadipa_montserrat_{s}.c" for s in SIZES] +
                           [f"attadipa_montserrat_num_{s}.c" for s in NUMERAL_SIZES])
               if not (OUT_DIR / n).exists()]
    if missing:
        print("missing generated font(s): " + ", ".join(missing), file=sys.stderr)
        return 1
    print(f"fonts: inputs unchanged, "
          f"{len(SIZES) + len(NUMERAL_SIZES)} generated file(s) present")
    return 0


if __name__ == "__main__":
    sys.exit(main())
